In [3]:
import fastf1

fastf1.Cache.enable_cache("../cache")

print("FastF1 is ready!")

FastF1 is ready!

In [4]:
session = fastf1.get_session(2026, "China", "Q")
session.load()

core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '81', '1', '10', '3', '6', '87', '27', '43', '31', '30', '41', '5', '55', '23', '14', '77', '18', '11']

In [5]:
session.results.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,,NaN,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,2.0,,NaN,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,3.0,,NaN,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,,NaN,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,,NaN,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000,NaT,,NaN,NaN

In [6]:
session.results.columns

Index(['DriverNumber', 'BroadcastName', 'Abbreviation', 'DriverId', 'TeamName',
       'TeamColor', 'TeamId', 'FirstName', 'LastName', 'FullName',
       'HeadshotUrl', 'CountryCode', 'Position', 'ClassifiedPosition',
       'GridPosition', 'Q1', 'Q2', 'Q3', 'Time', 'Status', 'Points', 'Laps'],
      dtype='object')

In [7]:
session.results.info()

<class 'fastf1.core.SessionResults'>
Index: 22 entries, 12 to 11
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   DriverNumber        22 non-null     object
 1   BroadcastName       22 non-null     object
 2   Abbreviation        22 non-null     object
 3   DriverId            22 non-null     object
 4   TeamName            22 non-null     object
 5   TeamColor           22 non-null     object
 6   TeamId              22 non-null     object
 7   FirstName           22 non-null     object
 8   LastName            22 non-null     object
 9   FullName            22 non-null     object
 10  HeadshotUrl         22 non-null     object
 11  CountryCode         22 non-null     object
 12  Position            22 non-null     float64
 13  ClassifiedPosition  22 non-null     object
 14  GridPosition        0 non-null      float64
 15  Q1                  22 non-null     timedelta64[ns]
 16  Q2                  16 non-null     timedelta64[ns]
 17  Q3                  10 non-null     timedelta64[ns]
 18  Time                0 non-null      timedelta64[ns]
 19  Status              22 non-null     object
 20  Points              0 non-null      float64
 21  Laps                0 non-null      float64
dtypes: float64(4), object(14), timedelta64[ns](4)
memory usage: 4.0+ KB

In [8]:
session.results.describe()

,Position,GridPosition,Q1,Q2,Q3,Time,Points,Laps
count,22.000000,0.0,22,16,10,0,0.0,0.0
mean,11.500000,NaN,0 days 00:01:34.130000,0 days 00:01:33.154500,0 days 00:01:32.663900,NaT,NaN,NaN
std,6.493587,NaN,0 days 00:00:00.965544849,0 days 00:00:00.481537814,0 days 00:00:00.394105301,NaT,NaN,NaN
min,1.000000,NaN,0 days 00:01:33.175000,0 days 00:01:32.443000,0 days 00:01:32.064000,NaT,NaN,NaN
25%,6.250000,NaN,0 days 00:01:33.538500,0 days 00:01:32.824250,0 days 00:01:32.418250,NaT,NaN,NaN
50%,11.500000,NaN,0 days 00:01:33.737500,0 days 00:01:33.163500,0 days 00:01:32.579000,NaT,NaN,NaN
75%,16.750000,NaN,0 days 00:01:34.272500,0 days 00:01:33.402250,0 days 00:01:32.969750,NaT,NaN,NaN
max,22.000000,NaN,0 days 00:01:36.906000,0 days 00:01:33.965000,0 days 00:01:33.292000,NaT,NaN,NaN

In [9]:
session.results[["Abbreviation", "TeamName", "Position"]]

   Abbreviation         TeamName  Position
12          ANT         Mercedes       1.0
63          RUS         Mercedes       2.0
44          HAM          Ferrari       3.0
16          LEC          Ferrari       4.0
81          PIA          McLaren       5.0
1           NOR          McLaren       6.0
10          GAS           Alpine       7.0
3           VER  Red Bull Racing       8.0
6           HAD  Red Bull Racing       9.0
87          BEA     Haas F1 Team      10.0
27          HUL             Audi      11.0
43          COL           Alpine      12.0
31          OCO     Haas F1 Team      13.0
30          LAW     Racing Bulls      14.0
41          LIN     Racing Bulls      15.0
5           BOR             Audi      16.0
55          SAI         Williams      17.0
23          ALB         Williams      18.0
14          ALO     Aston Martin      19.0
77          BOT         Cadillac      20.0
18          STR     Aston Martin      21.0
11          PER         Cadillac      22.0

In [10]:
session.results[["FullName", "TeamName", "Q1", "Q2", "Q3"]]

,FullName,TeamName,Q1,Q2,Q3
12,Kimi Antonelli,Mercedes,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000
63,George Russell,Mercedes,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000
44,Lewis Hamilton,Ferrari,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000
16,Charles Leclerc,Ferrari,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000
81,Oscar Piastri,McLaren,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000
1,Lando Norris,McLaren,0 days 00:01:33.535000,0 days 00:01:32.910000,0 days 00:01:32.608000
10,Pierre Gasly,Alpine,0 days 00:01:33.788000,0 days 00:01:33.003000,0 days 00:01:32.873000
3,Max Verstappen,Red Bull Racing,0 days 00:01:33.417000,0 days 00:01:33.098000,0 days 00:01:33.002000
6,Isack Hadjar,Red Bull Racing,0 days 00:01:33.632000,0 days 00:01:33.352000,0 days 00:01:33.121000
87,Oliver Bearman,Haas F1 Team,0 days 00:01:33.687000,0 days 00:01:33.197000,0 days 00:01:33.292000
27,Nico Hulkenberg,Audi,0 days 00:01:34.116000,0 days 00:01:33.354000,NaT
43,Franco Colapinto,Alpine,0 days 00:01:33.634000,0 days 00:01:33.357000,NaT
31,Esteban Ocon,Haas F1 Team,0 days 00:01:33.974000,0 days 00:01:33.538000,NaT
30,Liam Lawson,Racing Bulls,0 days 00:01:34.139000,0 days 00:01:33.765000,NaT
41,Arvid Lindblad,Racing Bulls,0 days 00:01:33.906000,0 days 00:01:33.784000,NaT
5,Gabriel Bortoleto,Audi,0 days 00:01:33.549000,0 days 00:01:33.965000,NaT
55,Carlos Sainz,Williams,0 days 00:01:34.317000,NaT,NaT
23,Alexander Albon,Williams,0 days 00:01:34.772000,NaT,NaT
14,Fernando Alonso,Aston Martin,0 days 00:01:35.203000,NaT,NaT
77,Valtteri Bottas,Cadillac,0 days 00:01:35.436000,NaT,NaT
18,Lance Stroll,Aston Martin,0 days 00:01:35.995000,NaT,NaT
11,Sergio Perez,Cadillac,0 days 00:01:36.906000,NaT,NaT

In [11]:
session.results.sort_values("Position")

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,,NaN,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,2.0,,NaN,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,3.0,,NaN,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,,NaN,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,,NaN,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000,NaT,,NaN,NaN
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,6.0,,NaN,0 days 00:01:33.535000,0 days 00:01:32.910000,0 days 00:01:32.608000,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,7.0,,NaN,0 days 00:01:33.788000,0 days 00:01:33.003000,0 days 00:01:32.873000,NaT,,NaN,NaN
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,8.0,,NaN,0 days 00:01:33.417000,0 days 00:01:33.098000,0 days 00:01:33.002000,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,9.0,,NaN,0 days 00:01:33.632000,0 days 00:01:33.352000,0 days 00:01:33.121000,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,10.0,,NaN,0 days 00:01:33.687000,0 days 00:01:33.197000,0 days 00:01:33.292000,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,11.0,,NaN,0 days 00:01:34.116000,0 days 00:01:33.354000,NaT,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,12.0,,NaN,0 days 00:01:33.634000,0 days 00:01:33.357000,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,13.0,,NaN,0 days 00:01:33.974000,0 days 00:01:33.538000,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,14.0,,NaN,0 days 00:01:34.139000,0 days 00:01:33.765000,NaT,NaT,,NaN,NaN
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,15.0,,NaN,0 days 00:01:33.906000,0 days 00:01:33.784000,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,16.0,,NaN,0 days 00:01:33.549000,0 days 00:01:33.965000,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,17.0,,NaN,0 days 00:01:34.317000,NaT,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,18.0,,NaN,0 days 00:01:34.772000,NaT,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,19.0,,NaN,0 days 00:01:35.203000,NaT,NaT,NaT,,NaN,NaN
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,20.0,,NaN,0 days 00:01:35.436000,NaT,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,21.0,,NaN,0 days 00:01:35.995000,NaT,NaT,NaT,,NaN,NaN
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,22.0,,NaN,0 days 00:01:36.906000,NaT,NaT,NaT,,NaN,NaN

In [12]:
session.results.sort_values("Q1")

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,,NaN,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,2.0,,NaN,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,,NaN,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000,NaT,,NaN,NaN
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,8.0,,NaN,0 days 00:01:33.417000,0 days 00:01:33.098000,0 days 00:01:33.002000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,3.0,,NaN,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000,NaT,,NaN,NaN
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,6.0,,NaN,0 days 00:01:33.535000,0 days 00:01:32.910000,0 days 00:01:32.608000,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,16.0,,NaN,0 days 00:01:33.549000,0 days 00:01:33.965000,NaT,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,,NaN,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,9.0,,NaN,0 days 00:01:33.632000,0 days 00:01:33.352000,0 days 00:01:33.121000,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,12.0,,NaN,0 days 00:01:33.634000,0 days 00:01:33.357000,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,10.0,,NaN,0 days 00:01:33.687000,0 days 00:01:33.197000,0 days 00:01:33.292000,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,7.0,,NaN,0 days 00:01:33.788000,0 days 00:01:33.003000,0 days 00:01:32.873000,NaT,,NaN,NaN
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,15.0,,NaN,0 days 00:01:33.906000,0 days 00:01:33.784000,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,13.0,,NaN,0 days 00:01:33.974000,0 days 00:01:33.538000,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,11.0,,NaN,0 days 00:01:34.116000,0 days 00:01:33.354000,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,14.0,,NaN,0 days 00:01:34.139000,0 days 00:01:33.765000,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,17.0,,NaN,0 days 00:01:34.317000,NaT,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,18.0,,NaN,0 days 00:01:34.772000,NaT,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,19.0,,NaN,0 days 00:01:35.203000,NaT,NaT,NaT,,NaN,NaN
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,20.0,,NaN,0 days 00:01:35.436000,NaT,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,21.0,,NaN,0 days 00:01:35.995000,NaT,NaT,NaT,,NaN,NaN
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,22.0,,NaN,0 days 00:01:36.906000,NaT,NaT,NaT,,NaN,NaN

In [13]:
session.results[
    session.results["TeamName"] == "Ferrari"
]

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,3.0,,NaN,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,,NaN,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000,NaT,,NaN,NaN

In [14]:
session.results[
    session.results["TeamName"] == "Mercedes"
]

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,,NaN,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,2.0,,NaN,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000,NaT,,NaN,NaN

In [15]:
qualifying_summary = session.results[
    ["Abbreviation", "TeamName", "Position", "Q1", "Q2", "Q3"]
]

In [16]:
qualifying_summary

,Abbreviation,TeamName,Position,Q1,Q2,Q3
12,ANT,Mercedes,1.0,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000
63,RUS,Mercedes,2.0,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000
44,HAM,Ferrari,3.0,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000
16,LEC,Ferrari,4.0,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000
81,PIA,McLaren,5.0,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000
1,NOR,McLaren,6.0,0 days 00:01:33.535000,0 days 00:01:32.910000,0 days 00:01:32.608000
10,GAS,Alpine,7.0,0 days 00:01:33.788000,0 days 00:01:33.003000,0 days 00:01:32.873000
3,VER,Red Bull Racing,8.0,0 days 00:01:33.417000,0 days 00:01:33.098000,0 days 00:01:33.002000
6,HAD,Red Bull Racing,9.0,0 days 00:01:33.632000,0 days 00:01:33.352000,0 days 00:01:33.121000
87,BEA,Haas F1 Team,10.0,0 days 00:01:33.687000,0 days 00:01:33.197000,0 days 00:01:33.292000
27,HUL,Audi,11.0,0 days 00:01:34.116000,0 days 00:01:33.354000,NaT
43,COL,Alpine,12.0,0 days 00:01:33.634000,0 days 00:01:33.357000,NaT
31,OCO,Haas F1 Team,13.0,0 days 00:01:33.974000,0 days 00:01:33.538000,NaT
30,LAW,Racing Bulls,14.0,0 days 00:01:34.139000,0 days 00:01:33.765000,NaT
41,LIN,Racing Bulls,15.0,0 days 00:01:33.906000,0 days 00:01:33.784000,NaT
5,BOR,Audi,16.0,0 days 00:01:33.549000,0 days 00:01:33.965000,NaT
55,SAI,Williams,17.0,0 days 00:01:34.317000,NaT,NaT
23,ALB,Williams,18.0,0 days 00:01:34.772000,NaT,NaT
14,ALO,Aston Martin,19.0,0 days 00:01:35.203000,NaT,NaT
77,BOT,Cadillac,20.0,0 days 00:01:35.436000,NaT,NaT
18,STR,Aston Martin,21.0,0 days 00:01:35.995000,NaT,NaT
11,PER,Cadillac,22.0,0 days 00:01:36.906000,NaT,NaT

In [2]:
import fastf1

fastf1.Cache.enable_cache("../cache")

In [3]:
session = fastf1.get_session(2026, "China", "Q")
session.load()

core           INFO 	Loading data for Chinese Grand Prix - Qualifying [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '44', '16', '81', '1', '10', '3', '6', '87', '27', '43', '31', '30', '41', '5', '55', '23', '14', '77', '18', '11']

In [4]:
session.results.describe()

,Position,GridPosition,Q1,Q2,Q3,Time,Points,Laps
count,22.000000,0.0,22,16,10,0,0.0,0.0
mean,11.500000,NaN,0 days 00:01:34.130000,0 days 00:01:33.154500,0 days 00:01:32.663900,NaT,NaN,NaN
std,6.493587,NaN,0 days 00:00:00.965544849,0 days 00:00:00.481537814,0 days 00:00:00.394105301,NaT,NaN,NaN
min,1.000000,NaN,0 days 00:01:33.175000,0 days 00:01:32.443000,0 days 00:01:32.064000,NaT,NaN,NaN
25%,6.250000,NaN,0 days 00:01:33.538500,0 days 00:01:32.824250,0 days 00:01:32.418250,NaT,NaN,NaN
50%,11.500000,NaN,0 days 00:01:33.737500,0 days 00:01:33.163500,0 days 00:01:32.579000,NaT,NaN,NaN
75%,16.750000,NaN,0 days 00:01:34.272500,0 days 00:01:33.402250,0 days 00:01:32.969750,NaT,NaN,NaN
max,22.000000,NaN,0 days 00:01:36.906000,0 days 00:01:33.965000,0 days 00:01:33.292000,NaT,NaN,NaN

In [5]:
session.results["TeamName"]

12           Mercedes
63           Mercedes
44            Ferrari
16            Ferrari
81            McLaren
1             McLaren
10             Alpine
3     Red Bull Racing
6     Red Bull Racing
87       Haas F1 Team
27               Audi
43             Alpine
31       Haas F1 Team
30       Racing Bulls
41       Racing Bulls
5                Audi
55           Williams
23           Williams
14       Aston Martin
77           Cadillac
18       Aston Martin
11           Cadillac
Name: TeamName, dtype: object

In [6]:
session.results[["Abbreviation", "TeamName", "Position"]]

   Abbreviation         TeamName  Position
12          ANT         Mercedes       1.0
63          RUS         Mercedes       2.0
44          HAM          Ferrari       3.0
16          LEC          Ferrari       4.0
81          PIA          McLaren       5.0
1           NOR          McLaren       6.0
10          GAS           Alpine       7.0
3           VER  Red Bull Racing       8.0
6           HAD  Red Bull Racing       9.0
87          BEA     Haas F1 Team      10.0
27          HUL             Audi      11.0
43          COL           Alpine      12.0
31          OCO     Haas F1 Team      13.0
30          LAW     Racing Bulls      14.0
41          LIN     Racing Bulls      15.0
5           BOR             Audi      16.0
55          SAI         Williams      17.0
23          ALB         Williams      18.0
14          ALO     Aston Martin      19.0
77          BOT         Cadillac      20.0
18          STR     Aston Martin      21.0
11          PER         Cadillac      22.0

In [7]:
session.results[
    ["FullName", "TeamName", "Q1", "Q2", "Q3"]
]

,FullName,TeamName,Q1,Q2,Q3
12,Kimi Antonelli,Mercedes,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000
63,George Russell,Mercedes,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000
44,Lewis Hamilton,Ferrari,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000
16,Charles Leclerc,Ferrari,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000
81,Oscar Piastri,McLaren,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000
1,Lando Norris,McLaren,0 days 00:01:33.535000,0 days 00:01:32.910000,0 days 00:01:32.608000
10,Pierre Gasly,Alpine,0 days 00:01:33.788000,0 days 00:01:33.003000,0 days 00:01:32.873000
3,Max Verstappen,Red Bull Racing,0 days 00:01:33.417000,0 days 00:01:33.098000,0 days 00:01:33.002000
6,Isack Hadjar,Red Bull Racing,0 days 00:01:33.632000,0 days 00:01:33.352000,0 days 00:01:33.121000
87,Oliver Bearman,Haas F1 Team,0 days 00:01:33.687000,0 days 00:01:33.197000,0 days 00:01:33.292000
27,Nico Hulkenberg,Audi,0 days 00:01:34.116000,0 days 00:01:33.354000,NaT
43,Franco Colapinto,Alpine,0 days 00:01:33.634000,0 days 00:01:33.357000,NaT
31,Esteban Ocon,Haas F1 Team,0 days 00:01:33.974000,0 days 00:01:33.538000,NaT
30,Liam Lawson,Racing Bulls,0 days 00:01:34.139000,0 days 00:01:33.765000,NaT
41,Arvid Lindblad,Racing Bulls,0 days 00:01:33.906000,0 days 00:01:33.784000,NaT
5,Gabriel Bortoleto,Audi,0 days 00:01:33.549000,0 days 00:01:33.965000,NaT
55,Carlos Sainz,Williams,0 days 00:01:34.317000,NaT,NaT
23,Alexander Albon,Williams,0 days 00:01:34.772000,NaT,NaT
14,Fernando Alonso,Aston Martin,0 days 00:01:35.203000,NaT,NaT
77,Valtteri Bottas,Cadillac,0 days 00:01:35.436000,NaT,NaT
18,Lance Stroll,Aston Martin,0 days 00:01:35.995000,NaT,NaT
11,Sergio Perez,Cadillac,0 days 00:01:36.906000,NaT,NaT

In [8]:
session.results.sort_values("Position")

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,,NaN,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,2.0,,NaN,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,3.0,,NaN,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,,NaN,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,,NaN,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000,NaT,,NaN,NaN
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,6.0,,NaN,0 days 00:01:33.535000,0 days 00:01:32.910000,0 days 00:01:32.608000,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,7.0,,NaN,0 days 00:01:33.788000,0 days 00:01:33.003000,0 days 00:01:32.873000,NaT,,NaN,NaN
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,8.0,,NaN,0 days 00:01:33.417000,0 days 00:01:33.098000,0 days 00:01:33.002000,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,9.0,,NaN,0 days 00:01:33.632000,0 days 00:01:33.352000,0 days 00:01:33.121000,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,10.0,,NaN,0 days 00:01:33.687000,0 days 00:01:33.197000,0 days 00:01:33.292000,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,11.0,,NaN,0 days 00:01:34.116000,0 days 00:01:33.354000,NaT,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,12.0,,NaN,0 days 00:01:33.634000,0 days 00:01:33.357000,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,13.0,,NaN,0 days 00:01:33.974000,0 days 00:01:33.538000,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,14.0,,NaN,0 days 00:01:34.139000,0 days 00:01:33.765000,NaT,NaT,,NaN,NaN
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,15.0,,NaN,0 days 00:01:33.906000,0 days 00:01:33.784000,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,16.0,,NaN,0 days 00:01:33.549000,0 days 00:01:33.965000,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,17.0,,NaN,0 days 00:01:34.317000,NaT,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,18.0,,NaN,0 days 00:01:34.772000,NaT,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,19.0,,NaN,0 days 00:01:35.203000,NaT,NaT,NaT,,NaN,NaN
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,20.0,,NaN,0 days 00:01:35.436000,NaT,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,21.0,,NaN,0 days 00:01:35.995000,NaT,NaT,NaT,,NaN,NaN
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,22.0,,NaN,0 days 00:01:36.906000,NaT,NaT,NaT,,NaN,NaN

In [9]:
session.results.sort_values("Position", ascending=False)

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
11,11,S PEREZ,PER,perez,Cadillac,909090,cadillac,Sergio,Perez,Sergio Perez,...,22.0,,NaN,0 days 00:01:36.906000,NaT,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,stroll,Aston Martin,229971,aston_martin,Lance,Stroll,Lance Stroll,...,21.0,,NaN,0 days 00:01:35.995000,NaT,NaT,NaT,,NaN,NaN
77,77,V BOTTAS,BOT,bottas,Cadillac,909090,cadillac,Valtteri,Bottas,Valtteri Bottas,...,20.0,,NaN,0 days 00:01:35.436000,NaT,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,alonso,Aston Martin,229971,aston_martin,Fernando,Alonso,Fernando Alonso,...,19.0,,NaN,0 days 00:01:35.203000,NaT,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,albon,Williams,1868DB,williams,Alexander,Albon,Alexander Albon,...,18.0,,NaN,0 days 00:01:34.772000,NaT,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,sainz,Williams,1868DB,williams,Carlos,Sainz,Carlos Sainz,...,17.0,,NaN,0 days 00:01:34.317000,NaT,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,bortoleto,Audi,F50537,audi,Gabriel,Bortoleto,Gabriel Bortoleto,...,16.0,,NaN,0 days 00:01:33.549000,0 days 00:01:33.965000,NaT,NaT,,NaN,NaN
41,41,A LINDBLAD,LIN,arvid_lindblad,Racing Bulls,6C98FF,rb,Arvid,Lindblad,Arvid Lindblad,...,15.0,,NaN,0 days 00:01:33.906000,0 days 00:01:33.784000,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,lawson,Racing Bulls,6C98FF,rb,Liam,Lawson,Liam Lawson,...,14.0,,NaN,0 days 00:01:34.139000,0 days 00:01:33.765000,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,ocon,Haas F1 Team,9C9FA2,haas,Esteban,Ocon,Esteban Ocon,...,13.0,,NaN,0 days 00:01:33.974000,0 days 00:01:33.538000,NaT,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,colapinto,Alpine,00A1E8,alpine,Franco,Colapinto,Franco Colapinto,...,12.0,,NaN,0 days 00:01:33.634000,0 days 00:01:33.357000,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,hulkenberg,Audi,F50537,audi,Nico,Hulkenberg,Nico Hulkenberg,...,11.0,,NaN,0 days 00:01:34.116000,0 days 00:01:33.354000,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,bearman,Haas F1 Team,9C9FA2,haas,Oliver,Bearman,Oliver Bearman,...,10.0,,NaN,0 days 00:01:33.687000,0 days 00:01:33.197000,0 days 00:01:33.292000,NaT,,NaN,NaN
6,6,I HADJAR,HAD,hadjar,Red Bull Racing,4781D7,red_bull,Isack,Hadjar,Isack Hadjar,...,9.0,,NaN,0 days 00:01:33.632000,0 days 00:01:33.352000,0 days 00:01:33.121000,NaT,,NaN,NaN
3,3,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,4781D7,red_bull,Max,Verstappen,Max Verstappen,...,8.0,,NaN,0 days 00:01:33.417000,0 days 00:01:33.098000,0 days 00:01:33.002000,NaT,,NaN,NaN
10,10,P GASLY,GAS,gasly,Alpine,00A1E8,alpine,Pierre,Gasly,Pierre Gasly,...,7.0,,NaN,0 days 00:01:33.788000,0 days 00:01:33.003000,0 days 00:01:32.873000,NaT,,NaN,NaN
1,1,L NORRIS,NOR,norris,McLaren,F47600,mclaren,Lando,Norris,Lando Norris,...,6.0,,NaN,0 days 00:01:33.535000,0 days 00:01:32.910000,0 days 00:01:32.608000,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,piastri,McLaren,F47600,mclaren,Oscar,Piastri,Oscar Piastri,...,5.0,,NaN,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000,NaT,,NaN,NaN
16,16,C LECLERC,LEC,leclerc,Ferrari,ED1131,ferrari,Charles,Leclerc,Charles Leclerc,...,4.0,,NaN,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,hamilton,Ferrari,ED1131,ferrari,Lewis,Hamilton,Lewis Hamilton,...,3.0,,NaN,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,russell,Mercedes,00D7B6,mercedes,George,Russell,George Russell,...,2.0,,NaN,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,antonelli,Mercedes,00D7B6,mercedes,Kimi,Antonelli,Kimi Antonelli,...,1.0,,NaN,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000,NaT,,NaN,NaN

In [10]:
session.results[
    session.results["TeamName"] == "Mercedes"
][["FullName", "Position", "Q1", "Q2", "Q3"]]

,FullName,Position,Q1,Q2,Q3
12,Kimi Antonelli,1.0,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000
63,George Russell,2.0,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000

In [11]:
qualifying_summary = session.results[
    ["FullName", "TeamName", "Position", "Q1", "Q2", "Q3"]
]

In [12]:
qualifying_summary

,FullName,TeamName,Position,Q1,Q2,Q3
12,Kimi Antonelli,Mercedes,1.0,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000
63,George Russell,Mercedes,2.0,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000
44,Lewis Hamilton,Ferrari,3.0,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000
16,Charles Leclerc,Ferrari,4.0,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000
81,Oscar Piastri,McLaren,5.0,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000
1,Lando Norris,McLaren,6.0,0 days 00:01:33.535000,0 days 00:01:32.910000,0 days 00:01:32.608000
10,Pierre Gasly,Alpine,7.0,0 days 00:01:33.788000,0 days 00:01:33.003000,0 days 00:01:32.873000
3,Max Verstappen,Red Bull Racing,8.0,0 days 00:01:33.417000,0 days 00:01:33.098000,0 days 00:01:33.002000
6,Isack Hadjar,Red Bull Racing,9.0,0 days 00:01:33.632000,0 days 00:01:33.352000,0 days 00:01:33.121000
87,Oliver Bearman,Haas F1 Team,10.0,0 days 00:01:33.687000,0 days 00:01:33.197000,0 days 00:01:33.292000
27,Nico Hulkenberg,Audi,11.0,0 days 00:01:34.116000,0 days 00:01:33.354000,NaT
43,Franco Colapinto,Alpine,12.0,0 days 00:01:33.634000,0 days 00:01:33.357000,NaT
31,Esteban Ocon,Haas F1 Team,13.0,0 days 00:01:33.974000,0 days 00:01:33.538000,NaT
30,Liam Lawson,Racing Bulls,14.0,0 days 00:01:34.139000,0 days 00:01:33.765000,NaT
41,Arvid Lindblad,Racing Bulls,15.0,0 days 00:01:33.906000,0 days 00:01:33.784000,NaT
5,Gabriel Bortoleto,Audi,16.0,0 days 00:01:33.549000,0 days 00:01:33.965000,NaT
55,Carlos Sainz,Williams,17.0,0 days 00:01:34.317000,NaT,NaT
23,Alexander Albon,Williams,18.0,0 days 00:01:34.772000,NaT,NaT
14,Fernando Alonso,Aston Martin,19.0,0 days 00:01:35.203000,NaT,NaT
77,Valtteri Bottas,Cadillac,20.0,0 days 00:01:35.436000,NaT,NaT
18,Lance Stroll,Aston Martin,21.0,0 days 00:01:35.995000,NaT,NaT
11,Sergio Perez,Cadillac,22.0,0 days 00:01:36.906000,NaT,NaT

In [13]:
qualifying_summary.sort_values("Position")

,FullName,TeamName,Position,Q1,Q2,Q3
12,Kimi Antonelli,Mercedes,1.0,0 days 00:01:33.305000,0 days 00:01:32.443000,0 days 00:01:32.064000
63,George Russell,Mercedes,2.0,0 days 00:01:33.262000,0 days 00:01:32.523000,0 days 00:01:32.286000
44,Lewis Hamilton,Ferrari,3.0,0 days 00:01:33.522000,0 days 00:01:32.567000,0 days 00:01:32.415000
16,Charles Leclerc,Ferrari,4.0,0 days 00:01:33.175000,0 days 00:01:32.486000,0 days 00:01:32.428000
81,Oscar Piastri,McLaren,5.0,0 days 00:01:33.590000,0 days 00:01:33.130000,0 days 00:01:32.550000
1,Lando Norris,McLaren,6.0,0 days 00:01:33.535000,0 days 00:01:32.910000,0 days 00:01:32.608000
10,Pierre Gasly,Alpine,7.0,0 days 00:01:33.788000,0 days 00:01:33.003000,0 days 00:01:32.873000
3,Max Verstappen,Red Bull Racing,8.0,0 days 00:01:33.417000,0 days 00:01:33.098000,0 days 00:01:33.002000
6,Isack Hadjar,Red Bull Racing,9.0,0 days 00:01:33.632000,0 days 00:01:33.352000,0 days 00:01:33.121000
87,Oliver Bearman,Haas F1 Team,10.0,0 days 00:01:33.687000,0 days 00:01:33.197000,0 days 00:01:33.292000
27,Nico Hulkenberg,Audi,11.0,0 days 00:01:34.116000,0 days 00:01:33.354000,NaT
43,Franco Colapinto,Alpine,12.0,0 days 00:01:33.634000,0 days 00:01:33.357000,NaT
31,Esteban Ocon,Haas F1 Team,13.0,0 days 00:01:33.974000,0 days 00:01:33.538000,NaT
30,Liam Lawson,Racing Bulls,14.0,0 days 00:01:34.139000,0 days 00:01:33.765000,NaT
41,Arvid Lindblad,Racing Bulls,15.0,0 days 00:01:33.906000,0 days 00:01:33.784000,NaT
5,Gabriel Bortoleto,Audi,16.0,0 days 00:01:33.549000,0 days 00:01:33.965000,NaT
55,Carlos Sainz,Williams,17.0,0 days 00:01:34.317000,NaT,NaT
23,Alexander Albon,Williams,18.0,0 days 00:01:34.772000,NaT,NaT
14,Fernando Alonso,Aston Martin,19.0,0 days 00:01:35.203000,NaT,NaT
77,Valtteri Bottas,Cadillac,20.0,0 days 00:01:35.436000,NaT,NaT
18,Lance Stroll,Aston Martin,21.0,0 days 00:01:35.995000,NaT,NaT
11,Sergio Perez,Cadillac,22.0,0 days 00:01:36.906000,NaT,NaT